main:
  params: [args]
  steps:
    - ingest_data:
        parallel:
          branches:
            - properties_branch:
                steps:
                  - extract_opa_properties:
                      call: http.post
                      args:
                        timeout: 1800
                        url: ${"https://" + sys.get_env("GOOGLE_CLOUD_LOCATION") + "-" + sys.get_env("GOOGLE_CLOUD_PROJECT_ID") + ".cloudfunctions.net/extract-opa-properties"}
                        auth:
                          type: OIDC
                  - prepare_opa_properties:
                      call: http.post
                      args:
                        timeout: 1800
                        url: ${"https://" + sys.get_env("GOOGLE_CLOUD_LOCATION") + "-" + sys.get_env("GOOGLE_CLOUD_PROJECT_ID") + ".cloudfunctions.net/prepare-opa-properties"}
                        auth:
                          type: OIDC
                  - load_opa_properties_source:
                      call: http.post
                      args:
                        timeout: 1800
                        url: ${"https://" + sys.get_env("GOOGLE_CLOUD_LOCATION") + "-" + sys.get_env("GOOGLE_CLOUD_PROJECT_ID") + ".cloudfunctions.net/run-sql"}
                        body:
                          sql: source/opa_properties.sql
                        auth:
                          type: OIDC
                  - load_opa_properties_core:
                      call: http.post
                      args:
                        timeout: 1800
                        url: ${"https://" + sys.get_env("GOOGLE_CLOUD_LOCATION") + "-" + sys.get_env("GOOGLE_CLOUD_PROJECT_ID") + ".cloudfunctions.net/run-sql"}
                        body:
                          sql: core/opa_properties.sql
                        auth:
                          type: OIDC
            - assessments_branch:
                steps:
                  - extract_opa_assessments:
                      call: http.post
                      args:
                        timeout: 1800
                        url: ${"https://" + sys.get_env("GOOGLE_CLOUD_LOCATION") + "-" + sys.get_env("GOOGLE_CLOUD_PROJECT_ID") + ".cloudfunctions.net/extract-opa-assessments"}
                        auth:
                          type: OIDC
                  - prepare_opa_assessments:
                      call: http.post
                      args:
                        timeout: 1800
                        url: ${"https://" + sys.get_env("GOOGLE_CLOUD_LOCATION") + "-" + sys.get_env("GOOGLE_CLOUD_PROJECT_ID") + ".cloudfunctions.net/prepare-opa-assessments"}
                        auth:
                          type: OIDC
                  - load_opa_assessments_source:
                      call: http.post
                      args:
                        timeout: 1800
                        url: ${"https://" + sys.get_env("GOOGLE_CLOUD_LOCATION") + "-" + sys.get_env("GOOGLE_CLOUD_PROJECT_ID") + ".cloudfunctions.net/run-sql"}
                        body:
                          sql: source/opa_assessments.sql
                        auth:
                          type: OIDC
                  - load_opa_assessments_core:
                      call: http.post
                      args:
                        timeout: 1800
                        url: ${"https://" + sys.get_env("GOOGLE_CLOUD_LOCATION") + "-" + sys.get_env("GOOGLE_CLOUD_PROJECT_ID") + ".cloudfunctions.net/run-sql"}
                        body:
                          sql: core/opa_assessments.sql
                        auth:
                          type: OIDC
            - pwd_parcels_branch:
                steps:
                  - extract_pwd_parcels:
                      call: http.post
                      args:
                        timeout: 1800
                        url: ${"https://" + sys.get_env("GOOGLE_CLOUD_LOCATION") + "-" + sys.get_env("GOOGLE_CLOUD_PROJECT_ID") + ".cloudfunctions.net/extract-pwd-parcels"}
                        auth:
                          type: OIDC
                  - prepare_pwd_parcels:
                      call: http.post
                      args:
                        timeout: 1800
                        url: ${"https://" + sys.get_env("GOOGLE_CLOUD_LOCATION") + "-" + sys.get_env("GOOGLE_CLOUD_PROJECT_ID") + ".cloudfunctions.net/prepare-pwd-parcels"}
                        auth:
                          type: OIDC
                  - load_pwd_parcels_source:
                      call: http.post
                      args:
                        timeout: 1800
                        url: ${"https://" + sys.get_env("GOOGLE_CLOUD_LOCATION") + "-" + sys.get_env("GOOGLE_CLOUD_PROJECT_ID") + ".cloudfunctions.net/run-sql"}
                        body:
                          sql: source/pwd_parcels.sql
                        auth:
                          type: OIDC
                  - load_pwd_parcels_core:
                      call: http.post
                      args:
                        timeout: 1800
                        url: ${"https://" + sys.get_env("GOOGLE_CLOUD_LOCATION") + "-" + sys.get_env("GOOGLE_CLOUD_PROJECT_ID") + ".cloudfunctions.net/run-sql"}
                        body:
                          sql: core/pwd_parcels.sql
                        auth:
                          type: OIDC
    - transform_data:
        steps:
          - derived_opa_residential_properties:
              call: http.post
              args:
                timeout: 1800
                url: ${"https://" + sys.get_env("GOOGLE_CLOUD_LOCATION") + "-" + sys.get_env("GOOGLE_CLOUD_PROJECT_ID") + ".cloudfunctions.net/run-sql"}
                body:
                  sql: derived/opa_residential_properties.sql
                auth:
                  type: OIDC
          - tax_year_bins_branch:
              steps:
                - derived_tax_year_bins:
                    call: http.post
                    args:
                      timeout: 1800
                      url: ${"https://" + sys.get_env("GOOGLE_CLOUD_LOCATION") + "-" + sys.get_env("GOOGLE_CLOUD_PROJECT_ID") + ".cloudfunctions.net/run-sql"}
                      body:
                        sql: derived/tax_year_assessment_bins.sql
                      auth:
                        type: OIDC
    - export_geojson:
        steps:
          - derived_property_tile_info:
              call: http.post
              args:
                timeout: 1800
                url: ${"https://" + sys.get_env("GOOGLE_CLOUD_LOCATION") + "-" + sys.get_env("GOOGLE_CLOUD_PROJECT_ID") + ".cloudfunctions.net/run-sql"}
                body:
                  sql: derived/property_tile_info.sql
                auth:
                  type: OIDC
          - export_geojson:
              call: http.post
              args:
                timeout: 3600
                url: ${"https://" + sys.get_env("GOOGLE_CLOUD_LOCATION") + "-" + sys.get_env("GOOGLE_CLOUD_PROJECT_ID") + ".cloudfunctions.net/export-geojson"}
                auth:
                  type: OIDC
